---
# Kustomization for Tilt Development Environment (FluxCD)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitrepository.yaml
  - secretmanagerconfig-gcp.yaml  # GCP
  - secretmanagerconfig-aws.yaml  # AWS
  - secretmanagerconfig-azure.yaml  # Azure

# All resources are in the prod namespace:
# - Namespace: prod (defined in namespaces/namespace.yaml at top level)
# - GitRepository: prod (defined in gitrepository.yaml) - FluxCD source
# - SecretManagerConfig: prod (defined in secretmanagerconfig.yaml) - references GitRepository
