---
# Kustomization for Tilt Development Environment (FluxCD)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gitrepository.yaml
  - secretmanagerconfig.yaml

# All resources are in the tilt namespace:
# - Namespace: tilt (defined in namespace.yaml)
# - GitRepository: tilt (defined in gitrepository.yaml) - FluxCD source
# - SecretManagerConfig: tilt (defined in secretmanagerconfig.yaml) - references GitRepository
