---
# Kustomization for Production Environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gitrepository.yaml
  - secretmanagerconfig.yaml

# All resources are in the prod namespace:
# - Namespace: prod (defined in namespace.yaml)
# - GitRepository: prod (defined in gitrepository.yaml)
# - SecretManagerConfig: prod (defined in secretmanagerconfig.yaml)
