---
# Kustomization for Tilt Development Environment (ArgoCD)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - secretmanagerconfig-gcp.yaml  # GCP
  - secretmanagerconfig-aws.yaml  # AWS
  - secretmanagerconfig-azure.yaml  # Azure

# All resources are in the tilt namespace:
# - Namespace: tilt (defined in namespaces/namespace.yaml at top level)
# - Application: tilt (defined in application.yaml) - ArgoCD source
# - SecretManagerConfig: tilt (defined in secretmanagerconfig.yaml) - references Application

